GPIO, I2C periphery, Input/OutputDriver interface, Input/OutputGPIO driver, ButtonInput device
CircuitMess/CMF pull request #1
Opened 2024-08-28 07:57 UTC by MiLeG

2024-08-29 11:41 UTC, Fr0zen3k requested changes

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/InputGPIO.h
> +	InputGPIO(const std::vector<InputPinDef>& inputs, StrongObjectPtr<GPIO> gpio);
Umjesto da passas gpio ptr kroz konstruktor, koristi SubclassOf<GPIO>, gettaj ga iz Application instancea po klasi, tako da je useru sto jednostavnije to koristiti kroz sto manje koda, jer ce inace user ovog drivera sam morati gettati gpio instance koji zeli

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/Interface/InputDriver.h
> +
extra lmfao

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/Interface/OutputDriver.cpp
> +		CMF_LOG(LogCMF, Error, "Port %d not registered", port);
Same as input driver, return da ne dodajes extra key u mapu

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/Interface/OutputDriver.cpp
> +		CMF_LOG(LogCMF, Error, "Port %d not registered", port);
Also na oba razreda stavi da je funkcija const

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/Interface/OutputDriver.h
> +
Extra lajn

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/Interface/OutputDriver.h
> +	class OutputDriver* driver;
Ista stvar kao i za InputPin sa SubclassOf

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/OutputGPIO.cpp
> +	gpio->write(pin, value ^ inversions[port]);
Svaki put kad na mapi koristis operator [] bez da prije provjeris jel taj key vec postoji unutra, dodas u mapu daj key sa default value sto je best case scenario waste of memory and performance ali u nekim slucajevima mozes bez da zelis dodat npr port koji ce se skenirati za input a nije intended for it, ili port na koji se moze writeat a nije intended for it

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/OutputGPIO.h
> +
znas i sam xd

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Drivers/OutputGPIO.h
> +	OutputGPIO(const std::vector<OutputPinDef>& outputs, StrongObjectPtr<GPIO> gpio);
Same as InputGPIO sa SubclassOf

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Devices/ButtonInput.h
> +	std::set<InputDriver*> inputSources;
Ovo bi trebali biti smart ptrs

2024-08-29 11:41 UTC, Fr0zen3k commented on src/Devices/ButtonInput.cpp
> +	const auto& inputPin = buttons[button];
Pazi kod accessa mape sa operatorom [], ostavio sam detaljniji komentar o ovom vec negdje

2024-08-29 11:42 UTC, Fr0zen3k commented on src/Devices/ButtonInput.h
> +	std::set<InputDriver*> inputSources;
also extra line hahah

2024-09-04 07:48 UTC, MiLeG commented on src/Drivers/Interface/InputDriver.h
> +
Nije bilo u docsima navedeno, ali budem.

2024-11-26 10:01 UTC, Fr0zen3k approved these changes

2024-11-26 10:01 UTC, merged